### ISSUE TITLE
Stack trace when requesting status for a request ID that doesn't exist

### ISSUE THREAD

**Issue by dchaddock** [aurorax-space/pyaurorax#67]
When requesting information for a search request using an identifier that doesn't exist, the library barfs a stack trace. We can improve the error handling a bit in the `AuroraXRequest` class.

The stack trace:
```
Traceback (most recent call last):
  File "/home/darrenc/miniconda3/envs/pyaurorax38/bin/aurorax-cli", line 5, in <module>
    cli()
  File "/home/darrenc/miniconda3/envs/pyaurorax38/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/darrenc/miniconda3/envs/pyaurorax38/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/darrenc/miniconda3/envs/pyaurorax38/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/darrenc/miniconda3/envs/pyaurorax38/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/darrenc/miniconda3/envs/pyaurorax38/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/darrenc/miniconda3/envs/pyaurorax38/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/darrenc/miniconda3/envs/pyaurorax38/lib/python3.8/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/src/aurorax/pyaurorax/pyaurorax/cli/conjunctions/commands.py", line 38, in get_status
    s = pyaurorax.requests.get_status(url)
  File "/usr/local/src/aurorax/pyaurorax/pyaurorax/requests/requests.py", line 35, in get_status
    res = req.execute()
  File "/usr/local/src/aurorax/pyaurorax/pyaurorax/api/classes/request.py", line 137, in execute
    req.json()["error_message"]))
KeyError: 'error_message'
```

**Comment by dchaddock** [comment]
Bugfix implemented and will be part of 0.9.0 release.
